packageExtensions:
  "@cauriland/core-kernel@*":
    dependencies:
      "@cauriland/core-api": latest
      "@cauriland/core-blockchain": latest
      "@cauriland/core-database": latest
      "@cauriland/core-forger": latest
      "@cauriland/core-logger-pino": latest
      "@cauriland/core-magistrate-api": latest
      "@cauriland/core-magistrate-transactions": latest
      "@cauriland/core-p2p": latest
      "@cauriland/core-snapshots": latest
      "@cauriland/core-state": latest
      "@cauriland/core-transaction-pool": latest
      "@cauriland/core-transactions": latest
      "@cauriland/core-webhooks": latest
      "@caurihub/guardian-api": latest
      "@caurihub/guardian-transactions": latest
      "@caurihub/nft-base-api": latest
      "@caurihub/nft-base-transactions": latest
      "@caurihub/nft-exchange-api": latest
      "@caurihub/nft-exchange-transactions": latest
  "@cauriland/core-magistrate-api@*":
    dependencies:
      "@cauriland/crypto": latest
  "@cauriland/core-snapshots@*":
    dependencies:
      joi: latest
  "@cauriland/core-transaction-pool@*":
    dependencies:
      "@cauriland/core-magistrate-crypto": latest
  "@cauriland/core@*":
    dependencies:
      "@oclif/errors": latest
  "@cauriland/crypto@*":
    dependencies:
      "@types/node": latest
  "@types/eslint-plugin-prettier@*":
    dependencies:
      eslint: latest
  jest-circus@*:
    dependencies:
      slash: 3.0.0
  jest-util@*:
    dependencies:
      jest-runner: latest
  node-fetch@*:
    dependencies:
      domexception: latest
  pg-cursor@*:
    dependencies:
      pg: latest
  typeorm@*:
    dependencies:
      pg: latest
      pg-query-stream: latest

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
